Spaces => tabs and strip trailing whitespace

diff --git a/vpnshift b/vpnshift
--- a/vpnshift
+++ b/vpnshift
@@ -28,9 +28,9 @@ if not otherwise specified:
 "
 
 quick_die() {
-    format="$1"; shift
-    >&2 printf "${format}\n" "$@"
-    exit 1
+	format="$1"; shift
+	>&2 printf "${format}\n" "$@"
+	exit 1
 }
 
 die() {
@@ -87,17 +87,17 @@ clean_exit() {
 		>&2 echo "openvpn exited"
 	fi
 
-    # don't start cleaning up until openvpn is gone
-    hush ip netns delete "${namespace}"
-    hush rm --recursive --force "${namespace_dir}"
-    hush sysctl --quiet net.ipv4.ip_forward="${forward}"
-    if [ ! `pgrep firewalld` ]
-    then
-        echo "${rules}" | hush iptables-restore
-    else
-        echo "[firewalld] clearing firewalld state"
-        hush systemctl restart firewalld
-    fi  
+	# don't start cleaning up until openvpn is gone
+	hush ip netns delete "${namespace}"
+	hush rm --recursive --force "${namespace_dir}"
+	hush sysctl --quiet net.ipv4.ip_forward="${forward}"
+	if [ ! `pgrep firewalld` ]
+	then
+		echo "${rules}" | hush iptables-restore
+	else
+		echo "[firewalld] clearing firewalld state"
+		hush systemctl restart firewalld
+	fi
 
 	# Sometimes there's a lag for the veths to be deleted by linux, so we
 	# delete it manually.
@@ -119,7 +119,7 @@ main() {
 	while getopts "hdc:u:l:" opt; do
 		case "${opt}" in
 			h) quick_die "${usage}" ;;
-            d) _debug=1 ;;
+			d) _debug=1 ;;
 			c) config="$(realpath "${OPTARG}")" ;;
 			u) user="${OPTARG}" ;;
 			l) log="$(realpath "${OPTARG}")" ;;
@@ -169,59 +169,59 @@ main() {
 	# Set up NAT and IP forwarding
 	must sysctl --quiet net.ipv4.ip_forward=1
 
-    # check if we need to enable masquerading via firewalld for veth_default
-    if [ `pgrep firewalld` ]
-    then
-        echo "[firewalld] enabling firewalld based masquerading for ${veth_default}"
+	# check if we need to enable masquerading via firewalld for veth_default
+	if [ `pgrep firewalld` ]
+	then
+		echo "[firewalld] enabling firewalld based masquerading for ${veth_default}"
 
-        if [[ $(firewall-cmd --get-zones | grep "${namespace}") != *"${namespace}"* ]]
-        then
-            echo "[firewalld] creating permanent new zone ${namespace} with target default"
-            must firewall-cmd -q --permanent --new-zone="${namespace}"
-            must firewall-cmd -q --permanent --zone="${namespace}" --set-target="default"
-            must firewall-cmd -q --reload
-        fi
+		if [[ $(firewall-cmd --get-zones | grep "${namespace}") != *"${namespace}"* ]]
+		then
+			echo "[firewalld] creating permanent new zone ${namespace} with target default"
+			must firewall-cmd -q --permanent --new-zone="${namespace}"
+			must firewall-cmd -q --permanent --zone="${namespace}" --set-target="default"
+			must firewall-cmd -q --reload
+		fi
 
-        # add interface to our zone
-        echo "[firewalld] adding ${veth_default} and ${veth_vpn} to zone ${namespace}"
-        must firewall-cmd -q --zone="${namespace}" --change-interface="${veth_default}"
+		# add interface to our zone
+		echo "[firewalld] adding ${veth_default} and ${veth_vpn} to zone ${namespace}"
+		must firewall-cmd -q --zone="${namespace}" --change-interface="${veth_default}"
 
-        # apply our source range to our zone
-        echo "[firewalld] adding 10.10.10.10/31 as source for ${namespace}"
-        must firewall-cmd -q --zone="${namespace}" --add-source=10.10.10.10/31
+		# apply our source range to our zone
+		echo "[firewalld] adding 10.10.10.10/31 as source for ${namespace}"
+		must firewall-cmd -q --zone="${namespace}" --add-source=10.10.10.10/31
 
-        # enable masquerading from our new source range on the default zone
-        default_zone=$(firewall-cmd --get-default-zone)
-        echo "[firewalld] enabling masquerading on default zone: ${default_zone}"
-        must firewall-cmd -q --zone="${default_zone}" --add-masquerade
-        must firewall-cmd -q --zone="${default_zone}"  --add-rich-rule=\'rule family="ipv4" source address="10.10.10.10/31" masquerade\'
+		# enable masquerading from our new source range on the default zone
+		default_zone=$(firewall-cmd --get-default-zone)
+		echo "[firewalld] enabling masquerading on default zone: ${default_zone}"
+		must firewall-cmd -q --zone="${default_zone}" --add-masquerade
+		must firewall-cmd -q --zone="${default_zone}"  --add-rich-rule=\'rule family="ipv4" source address="10.10.10.10/31" masquerade\'
 
-        # optionally allow ports, services, etc. on our zone
+		# optionally allow ports, services, etc. on our zone
 
-        # enabling desired ports
-        #echo "enabling all port traffic on zone ${namespace}"
-        #must firewall-cmd -q --zone="${namespace}" --add-port=1025-65535/udp
-        #must firewall-cmd -q --zone="${namespace}" --add-port=1025-65535/tcp
+		# enabling desired ports
+		#echo "enabling all port traffic on zone ${namespace}"
+		#must firewall-cmd -q --zone="${namespace}" --add-port=1025-65535/udp
+		#must firewall-cmd -q --zone="${namespace}" --add-port=1025-65535/tcp
 
-        # enable services
-        #echo "enabling dns on zone ${namespace}"
-        #must firewall-cmd -q --zone="${namespace}" --add-service=dns
+		# enable services
+		#echo "enabling dns on zone ${namespace}"
+		#must firewall-cmd -q --zone="${namespace}" --add-service=dns
 
-    else
-        must iptables --table "nat" --append "POSTROUTING" --jump "MASQUERADE" --source "10.10.10.10/31"
-    fi
+	else
+		must iptables --table "nat" --append "POSTROUTING" --jump "MASQUERADE" --source "10.10.10.10/31"
+	fi
 
-    # Set up DNS inside the new namespace
+	# Set up DNS inside the new namespace
 	printf > "${namespace_dir}/resolv.conf" \
 		"nameserver %s\nnameserver %s\n" \
 		"108.62.19.131" \
 		"104.238.194.235"
 
-    # drop in a shell to debug namespace connectivity ... the exit trap will catch exit from this and clean up
-    if [ "$_debug" -eq 1 ]
-    then
-        ip netns exec "${namespace}" bash
-    fi
+	# drop in a shell to debug namespace connectivity ... the exit trap will catch exit from this and clean up
+	if [ "$_debug" -eq 1 ]
+	then
+		ip netns exec "${namespace}" bash
+	fi
 
 	# Launch openvpn
 
